language: java
jdk:
  - openjdk22
addons:
  sonarcloud:
  organization: "skyrimwell"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=skyrimwell -Dsonar.login=${SONAR_TOKEN}